services:
  machine1:
    build: .
    command: python3 agent.py --tcp-port 8900
    volumes:
      - ./shared1:/app/shared
      - ./downloads1:/app/downloads

  machine2:
    build: .
    command: python3 agent.py --tcp-port 8900
    volumes:
      - ./shared2:/app/shared
      - ./downloads2:/app/downloads

  machine3:
    build: .
    command: python3 agent.py --tcp-port 8900
    volumes:
      - ./shared3:/app/shared
      - ./downloads3:/app/downloads

  machine4:
    build: .
    command: python3 agent.py --tcp-port 8900
    volumes:
      - ./shared4:/app/shared
      - ./downloads4:/app/downloads

  machine5:
    build: .
    command: python3 agent.py --tcp-port 8900
    volumes:
      - ./shared5:/app/shared
      - ./downloads5:/app/downloads

networks:
  pa3:
    driver: bridge
